version: "3.8"

networks:
  attacker:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.10.10.0/24
          gateway: 10.10.10.1

  victim:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.20.20.0/24
          gateway: 10.20.20.1

