version: "3.8"

services:
  helper:
    build: 
      context: ./dockerfiles
      dockerfile: helper.Dockerfile
    container_name: helper
    hostname: helper
    ports:
      - "80:80" 
      - "9000:9000" 
    expose:
      - "80"
      - "9000"
    extra_hosts:
#      - "victim1:172.16.101.20"
       - "tomcat:10.20.20.22"
    networks:
      attacker:
        ipv4_address: 10.10.10.10
      victim:
        ipv4_address: 10.20.20.10


  tomcat:
    image: vulhub/tomcat:8.0
    build: 
      context: ./dockerfiles
      dockerfile: tomcat.Dockerfile
    container_name: tomcat
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
   
    ports:
     - "8080:8080"
    networks:
      victim:
        ipv4_address: 10.20.20.20
        
